service: amazon-list-price-reporter
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1

functions:
  api:
    handler: src/index.handler
    environment:
      AMAZON_WISHLIST_URL: ${env:AMAZON_WISHLIST_URL}
      CHANNEL_ACCESS_TOKEN: ${env:CHANNEL_ACCESS_TOKEN}
      CHANNEL_SECRET: ${env:CHANNEL_SECRET}
    timeout: 30
    events:
      - http:
          method: post
          path: "/webhook"
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
